init_config:

instances:
  - rabbitmq_api_url: http://localhost:15672/api/
    auth_type: basic
    username: datadog
    password: datadog

logs:
  - type: file
    path: /var/log/rabbitmq/*.log
    source: rabbitmq
    log_processing_rules:
      - type: multi_line
        name: logs_starts_with_equal_sign
        pattern: "="
