---
- name: "Create Nomad root configuration directory"
  ansible.builtin.file:
    path: /etc/nomad/
    state: directory

- name: "Deploy Nomad systemd service"
  ansible.builtin.copy:
    src: nomad@.service
    dest: /etc/systemd/system/nomad@.service
  notify: Reload systemd

- ansible.builtin.meta: flush_handlers

- include_tasks: instance.yml
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance
  vars:
    instance_name: "{{ instance.name }}"
    instance_address: "{{ instance.consul_address | ansible.netcommon.ipaddr('address') }}"
