---
- name: "Stop Nomad"
  ansible.builtin.systemd:
    name: nomad.service
    state: stopped
  ignore_errors: yes

- name: "Stop Consul"
  ansible.builtin.systemd:
    name: consul.service
    state: stopped
  ignore_errors: yes

- name: "Remove python3-docker"
  ansible.builtin.apt:
    name: python3-docker
    state: absent

- name: "Install python3-pip"
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: "Install Docker Python SDK"
  ansible.builtin.pip:
    name: docker
    version: "5.0.3"
    state: present

- name: "Get a list of all running containers"
  community.docker.docker_host_info:
    containers: true
  register: docker_info

- name: "Stop all running containers"
  community.docker.docker_container:
    name: '{{ item.Names[0] | regex_replace("^/", "") }}'
    state: stopped
  loop: '{{ docker_info.containers }}'

- name: "Prune everything in the Docker daemon"
  community.docker.docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
    builder_cache: yes

- name: "Umount all tmpfs"
  ansible.builtin.command:
    cmd: 'sh -c "umount /opt/nomad/alloc/*/*/secrets || true"'

- name: "Delete Nomad state directory"
  ansible.builtin.file:
    path: /opt/nomad
    state: absent

- name: "Create Nomad state directory"
  ansible.builtin.file:
    path: /opt/nomad
    state: directory
    owner: nomad
    group: nomad

- name: "Delete Consul state directory"
  ansible.builtin.file:
    path: /opt/consul
    state: absent

- name: "Create Consul state directory"
  ansible.builtin.file:
    path: /opt/consul
    state: directory
    owner: consul
    group: consul
