---
- name: "Add group 'minio'"
  ansible.builtin.group:
    name: minio
    state: present

- name: "Add user 'minio'"
  ansible.builtin.user:
    name: minio
    group: minio
    home: /opt/minio
    create_home: true
    system: true
    shell: /bin/false
    state: present

- name: "Deploy Minio systemd service"
  ansible.builtin.copy:
    src: minio.service
    dest: /etc/systemd/system/minio.service
  notify: Reload systemd

- name: "Deploy Minio environment variables"
  ansible.builtin.template:
    src: env
    dest: /etc/default/minio
  notify: Restart minio

- name: "Enable and start Minio"
  ansible.builtin.systemd:
    name: minio.service
    enabled: true
    state: started

- name: "Install python3-pip"
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: "Instal boto3"
  ansible.builtin.pip:
    name: boto3
    version: "1.21.43"
    state: present

- name: "Instal botocore"
  ansible.builtin.pip:
    name: botocore
    version: "1.21.43"
    state: present

- name: "Create bucket for each group"
  amazon.aws.s3_bucket:
    name: "{{ item.name }}"
    state: "present"
    aws_access_key: minioadmin
    aws_secret_key: minioadmin
    s3_url: "http://localhost:9000"
    aws_config: { signature_version: "s3v4" }
  loop: "{{ instance_groups }}"
