---
- name: "Add group 'consul'"
  ansible.builtin.group:
    name: consul
    state: present

- name: "Add user 'consul'"
  ansible.builtin.user:
    name: consul
    group: consul
    home: /opt/consul
    create_home: true
    system: true
    shell: /bin/false
    state: present

- name: "Create Consul root configuration directory"
  ansible.builtin.file:
    path: /etc/consul/
    owner: consul
    group: consul
    state: directory

- name: "Deploy Consul systemd service"
  ansible.builtin.copy:
    src: consul@.service
    dest: /etc/systemd/system/consul@.service
  notify: Reload systemd

- name: "Deploy Consul datadog config"
  ansible.builtin.template:
    src: datadog-config.yaml
    dest: /etc/datadog-agent/conf.d/consul.d/conf.yaml
  notify: Restart datadog-agent

- ansible.builtin.meta: flush_handlers

- include_tasks: instance.yml
  loop: "{{ instances }}"
  loop_control:
    loop_var: instance
  vars:
    instance_name: "{{ instance.name }}"
    instance_address: "{{ instance.consul_address | ansible.netcommon.ipaddr('address') }}"
