---
- name: "Create cloudflared configuration directory"
  ansible.builtin.file:
    path: /etc/cloudflared/
    state: directory

- name: "Deploy cloudflared cert"
  ansible.builtin.copy:
    dest: /etc/cloudflared/cert.pem
    content: "{{ cloudflared_cert }}"

- name: "Fetch the tunnel credentials"
  ansible.builtin.command:
    cmd: /usr/local/bin/cloudflared tunnel token --credentials-file /etc/cloudflared/{{ cloudflared_tunnel_uuid }}.json {{ cloudflared_tunnel_uuid }}
    creates: /etc/cloudflared/{{ cloudflared_tunnel_uuid }}.json

- name: "Deploy the tunnel config file"
  ansible.builtin.template:
    src: config.yml
    dest: /etc/cloudflared/config.yml
  notify: Restart cloudflared

- name: "Deploy cloudflared systemd service"
  ansible.builtin.copy:
    src: cloudflared.service
    dest: /etc/systemd/system/cloudflared.service
  notify: Reload systemd

- ansible.builtin.meta: flush_handlers

- name: "Enable and start cloudflared"
  ansible.builtin.systemd:
    name: cloudflared.service
    enabled: true
    state: started
