---
- name: "Install RabbitMQ"
  ansible.builtin.apt:
    state: present
    name:
      - erlang-base
      - erlang-asn1
      - erlang-crypto
      - erlang-eldap
      - erlang-ftp
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-parsetools
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - erlang-syntax-tools
      - erlang-tftp
      - erlang-tools
      - erlang-xmerl
      - rabbitmq-server

- name: "Enable management plugin"
  community.rabbitmq.rabbitmq_plugin:
    state: enabled
    name: rabbitmq_management

- name: "Create a vhost for each group"
  community.rabbitmq.rabbitmq_vhost:
    name: "{{ item.name }}"
  loop: "{{ instance_groups }}"

- name: "Create a user for each group"
  community.rabbitmq.rabbitmq_user:
    user: "{{ item.name }}"
    password: '{{ lookup("file", "./instructions/per-group/" + item.name + "/queue") }}'
    state: present
    tags: policymaker
    vhost: "{{ item.name }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
  loop: "{{ instance_groups }}"
